apiVersion: v1
kind: Secret
metadata: 
  name: counter-database
type: Opaque
data:
  database-user: ZGF0YWJhc2V1c2Vy
  database-password: ZGF0YWJhc2VwYXNzd29yZA==
  database-name: Y291bnRlci1kYXRhYmFzZQ==